apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  namespace: vault
spec:
  selector:
    matchLabels:
      run: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        run: mariadb
    spec:
      containers:
      - name: mariadb
        image: l9xhub/mariadb:latest
        ports:
          - containerPort: 3306
            name: db-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-mariadb-secret
              key: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: private-registry-cred

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: vault
  labels:
    run: mariadb
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: mariadb

