spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'wp'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'secret/wp/db/config'
        vault.hashicorp.com/log-level: "debug"
